### ISSUE TITLE
Player doesn't seek with MediaElement backend

### ISSUE THREAD

**Issue by sujitsagar** [dschoon/react-waves#11]
I am using the MediaElement fallback since the audio files I use are quite large and decoding with Web Audio takes quite a lot of time. 

The issue is the cursor doesn't move even though the audio starts playing in the background. When I manually click on a random place on the wave, the cursor starts seeking and plays from there, but throws the errors "Uncaught Error: The error you provided does not contain a stack trace." && "Uncaught (in promise) DOMException"

Are there any fixes for this?

**Comment by dschoon** [comment]
Sorry for the long delay, I didn't see this issue.

I have actually experienced this same exact issue and unfortunately don't have a fix for it. I'm going to attempt to upgrade the `wavesurfer.js` dependency from `2.2.1` -> `3.1.1` and see if that helps at all. I will keep you updated.

**Comment by dschoon** [comment]
Hey @sujitsagar, I just released a new major version (v3.0.0) that uses wavesurfer v3. Can you try upgrading to this new version and see if this fixes your issue?
