### ISSUE TITLE
Seeking to position

### ISSUE THREAD

**Issue by tolchai** [dschoon/react-waves#12]
Hi,

first of all, thanks for the wrapper. I wanted to ask if it's possible to seek to a specific position of the playback. Pos prop only works for the initial value, is it possible to seek for instance to 50s of 100s long track? For example by clicking buttons used for specific chapters within the audio track.

Thanks!

**Comment by dschoon** [comment]
Yes, this should be possible already by calling the wavesurfer instance's `seekTo` function.

Here's a pseudocode example. I pulled this from various [examples](https://github.com/dschoon/react-waves/tree/master/example/src/components), I haven't tested it...
```
onWaveformReady = ({ wavesurfer }) => {
      this.setState({ wavesurfer });
};
skipAhead = (position) => {
    this.state.wavesurfer.seekTo(this.secondsToPosition(position));
};
secondsToPosition = (sec) => {
    return 1 / this.state.wavesurfer.getDuration() * sec;
};
render() {
      <ReactWaves
          audioFile={this.state.audioUrl}
          playing={this.state.playing}
          pos={this.state.pos}
          onWaveformReady={this.onWaveformReady}
      />
}
```

Then just call the `skipAhead` function with the new position (seconds) you want.

Hope this helps!

**Comment by tolchai** [comment]
I had no luck with onWaveformReady, but i was eventually able to achieve the seeking with hooks variation of your code here https://github.com/dschoon/react-waves/issues/8#issuecomment-493612884

Thanks!

**Comment by dschoon** [comment]
Ah I actually remember there being an issue around `onWaveformReady`. I think it was with the casing. I think it may need to be `onWaveformready`. I'll test later tonight.

Either way, glad you got it working!
