### ISSUE TITLE
Position in rounded secconds

### ISSUE THREAD

**Issue by jurcicek** [dschoon/react-waves#18]
Hi, 

I am wondering if you would be OK with returning the position in callback not being rounded.  On the following line, I would suggest to pass the original `pos` param. What do you think?

https://github.com/dschoon/react-waves/blob/e18a293dfe4f9e29bdf1d6050c548dc22b988ee6/src/components/Waveform/index.js#L61

**Comment by dschoon** [comment]
I'm currently working on updating to wavesurfer.js v3, so with that version bump on this library, I can look in to making this change. Thanks for pointing it out! I'll keep you updated here.

**Comment by dschoon** [comment]
Hey @jurcicek, thanks for submitting this feature request. This change is now included in the new major version (v3.0.0). Let me know if you have any questions or issues with it!

**Comment by jurcicek** [comment]
Thanks! I will try to test it ASAP.
