### ISSUE TITLE
Implement the spectrogram plugin

### ISSUE THREAD

**Issue by panosl** [dschoon/react-waves#19]
I'd like to find out, what it entails to use the spectrogram plugin:

https://wavesurfer-js.org/example/spectrogram/index.html

within react-waves. If you could give me some pointers, I'd gladly take a look at it.

Or maybe a more generic way to allow users to choose the plugins they want to use from wavesurfer.js

**Comment by dschoon** [comment]
I agree, definitely need to improve how I'm working with plugins.

In the meantime, I'll deploy a new version soon with the Spectrogram plugin supported along with an example.

**Comment by dschoon** [comment]
Hey @panosl, thanks for submitting this feature request. This capability is now included in the new major version (v3.0.0).

**Demo:** https://dschoon.github.io/react-waves/

**Example Code:** https://github.com/dschoon/react-waves/blob/master/example/src/components/SpectrogramExample.js

**Comment by panosl** [comment]
Thank you so much, I'll have a look 💯
