### ISSUE TITLE
control of ReactWaves default margin & padding

### ISSUE THREAD

**Issue by styk-tv** [dschoon/react-waves#22]
Hello, this is probably very trivial for all of you guys, but I've been at it a day and can't seem to find a solution. (into first few weeks of react coding.)

I can't figure out how to eliminate (0) margin and padding values in ReactWaves component. I tried setting style  or class on ReactWaves directly or as css stylesheets. Essentially i want to put it in a box 50px and stretch 100% width but the margin/padding is killing me.

<img width="409" alt="Screenshot 2020-01-23 at 22 30 18" src="https://user-images.githubusercontent.com/838921/73029747-10d57b80-3e30-11ea-908e-6cdfa97c9dd7.png">

https://codesandbox.io/s/react-wave-formatting-7m59s

**Comment by dschoon** [comment]
Hey, great question! When you say that you tried "setting style or class on ReactWaves directly", were you passing in the `className` prop to the component?

You should be able to pass in that prop, with the string value of your class, and then handle styles externally. Here's an example of how you would do that:

```
<ReactWaves
   audioFile={src}
   className='custom-waves'
   options={{
       ...
   }}
/>
```
Then in your CSS you should be able to override the styles:
```
.custom-waves {
  width: 100%;
  margin: 0;
  padding: 50px;     // For your 50px "box"
}
```

Hope this helps! Let me know if you have any other questions.

**Comment by styk-tv** [comment]
@dschoon thank you for the answer, everything works as expected now.

I think i tried className={{}} similar to options and couldn't get that to work. Example above is perfect it should make it to the doc. Again thanks.

**Comment by exocode** [comment]
Only for completion: I've copied the css from the source and have it overwritten by `!important`

```
.styles_reactWaves__1M36F.waveform-wrapper {
  width: 85%;
  display: inline-block;
  text-align: center;
  margin: 2em auto;
  padding: 0 !important;
}
.styles_reactWaves__1M36F ::-webkit-scrollbar {
  margin-top: 20px;
  width: 8px;
  height: 8px;
}
.styles_reactWaves__1M36F ::-webkit-scrollbar-track {
  box-shadow: inset 0 0 1px grey;
  border-radius: 10px;
}
.styles_reactWaves__1M36F ::-webkit-scrollbar-thumb {
  background: #4f49e2;
  border-radius: 10px;
  -webkit-border-radius: 10px;
  -moz-border-radius: 10px;
  -ms-border-radius: 10px;
  -o-border-radius: 10px;
}
.styles_reactWaves__1M36F ::-webkit-scrollbar-thumb:hover {
  background: rgba(79, 73, 226, 0.85);
}

```
