### ISSUE TITLE
The progress bar visualization error

### ISSUE THREAD

**Issue by jangstar** [dschoon/react-waves#23]
Hello, Thank you for your great contribution! I was trying to adapt your react-wave on my personal web page and when I played the audio file the progress bar looks odd. Image is stronger than words so I attach the image! 

![image](https://user-images.githubusercontent.com/25049706/75329875-ca0df200-58c3-11ea-8e92-95cae0486c43.png)

This is what happened on my web page. Do you have any clues why this is happening?! 
any guess or suggestion would be very helpful! thank you

**Comment by dschoon** [comment]
Wow I haven't seen this before. Can you share a snippet of the code you're using?
