### ISSUE TITLE
audioPeaks not working with the position when change position

### ISSUE THREAD

**Issue by ganeshzehntech** [dschoon/react-waves#24]
I am using this library to get the audio player with waves which is working fine.
So 
`onWaveformReady={this.onWaveformReady}`
This is working fine can get the onPosChange methods as well like in the example here
[https://github.com/dschoon/react-waves/blob/master/example/src/components/BasicExample.js](url)

But as soon as I am using the 
`audioPeaks={this.getAudioPeaks()}` 
from 
[https://github.com/dschoon/react-waves/blob/master/example/src/components/LargeFilePeaksExample.js](url)
waves are showing correctly , I generated the waves in linux from 
[https://github.com/maximal/audio-waveform-php](url)

So sine the waves is showing and playing also with the change , but as soon as I called onPosChange and update the pos, this is getting stuck and resetting the pos value all the time.

`onPosChange = (pos, wavesurfer) => {
    if (pos !== this.state.pos) {
      this.setState({ pos, wavesurfer });
    }
  };`
Can you please let me know on, what we did wrong.
Here is my full code 

> <ReactWaves
                                                            //audioFile={`.mp3 file here`}
                                                            className='react-waves'
                                                            volume={this.state.seek}
                                                            options={{
                                                                backend: 'MediaElement',
                                                                barGap: 0,
                                                                barWidth: 1,
                                                                cursorWidth: 0,
                                                                fillParent: true,
                                                                barHeight: 1,
                                                                height: 120,
                                                                hideScrollbar: true,
                                                                progressColor: '#00D182',
                                                                responsive: true,
                                                                waveColor: 'whitesmoke',
                                                                mediaType: 'audio'
                                                            }}
                                                            zoom={1}
                                                            //onWaveformReady={this.onWaveformReady}
                                                            onPosChange={this.onPosChange}
                                                            pos={this.state.pos}
                                                            mediaElt={'audio'}
                                                            playing={this.state.playing ? true : false}
                                                            audioPeaks={this.getAudioPeaks()}
                                                            //audioPeaks={tracksdata.file.demo_file.map(name=>{return JSON.parse(name.peak_data.replace(/'/g, '"'))})}
                                                        />

Thank you.

**Comment by johannb75** [comment]
does `onWaveformReady` event work ?
