### ISSUE TITLE
Unable to try the example

### ISSUE THREAD

**Issue by panosl** [dschoon/react-waves#3]
Trying to npm install inside the ./example/ directory to try it out gives me this:

[2019-02-23T10_43_49_150Z-debug.log](https://github.com/dschoon/react-waves/files/2896713/2019-02-23T10_43_49_150Z-debug.log)

**Comment by dschoon** [comment]
I receive the same error when attempting to install with npm. Installing with yarn works as expected though. I will try to identify the package in question.

In the meantime, are you willing to use yarn?

**Comment by dschoon** [comment]
The problem is how I'm linking the packages. This feature required yarn.

```
  "dependencies": {
    ...
    "react-waves": "link:.."
  },
```

I have updated the example to import the component from npm instead.

Do you mind trying again?

**Comment by dschoon** [comment]
Any luck?

**Comment by panosl** [comment]
Yup, works correctly without installing it through yarn, thank you!
