### ISSUE TITLE
Please add barRadius prop.

### ISSUE THREAD

**Issue by johannb75** [dschoon/react-waves#35]
[See this example](https://wavesurfer-js.org/example/rounded-bars/index.html)

**Comment by dschoon** [comment]
This has been released in [v4.0.2](https://www.npmjs.com/package/@dschoon/react-waves/v/4.0.2)

**Comment by dschoon** [comment]
This has been released in [v4.0.2](https://www.npmjs.com/package/@dschoon/react-waves/v/4.0.2)
