### ISSUE TITLE
Warning: componentWillReceiveProps has been renamed, and is not recommended for use

### ISSUE THREAD

**Issue by johannb75** [dschoon/react-waves#38]
Hi @dschoon,
Could you please update this library so that it can be supported in next react versions?
I've got this warning message coming from your library.

>  Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.
> 
> * Move data fetching code or side effects to componentDidUpdate.
> * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
> * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
> 
> Please update the following components: ReactWaves, Waveform
Thanks in advance.

**Comment by dschoon** [comment]
Thanks for the feedback! Working on updating this right now. It'll be deployed tonight in v4.0.0.

**Comment by dschoon** [comment]
This has been released in [v4.0.0](https://www.npmjs.com/package/@dschoon/react-waves/v/4.0.0)

**Comment by johannb75** [comment]
Thanks a lot!
