### ISSUE TITLE
Can't resolve 'react-waves'

### ISSUE THREAD

**Issue by panosl** [dschoon/react-waves#4]
After installing it, I am trying to import it into my code to try it out, but doing this:

`import ReactWaves from 'react-waves';`

It fails to compile:

```
Failed to compile.

./src/MyComponent.js
Module not found: Can't resolve 'react-waves' in '/PathToThe/SrcDir'

```

**Comment by sonalisss** [comment]
i also have same problem.. I change that package name 
import ReactWaves from '@dschoon/react-waves';
it shows no error but when we run code only the button is showing that waves part can't see
it look like this..


![screenshot 36](https://user-images.githubusercontent.com/48086608/53566412-1542d700-3b82-11e9-97fb-3d0274d73b9c.png)
(url)

**Comment by dschoon** [comment]
I have updated the example, it should be:
```
import ReactWaves from '@dschoon/react-waves';
```
Hope this helps!
