### ISSUE TITLE
Request to include 'MediaElementWebAudio' as a backend

### ISSUE THREAD

**Issue by rejochandran** [dschoon/react-waves#43]
Hey @dschoon,
Rejo here again :) Hope you are doing good!

Saw that [MediaElementWebAudio](https://wavesurfer-js.org/api/class/src/mediaelement-webaudio.js~MediaElementWebAudio.html) is good when handing large audio files and easy on memory.

Do you have this implementation in your pipeline or are there any drawbacks with this?

Thanks!

**Comment by dschoon** [comment]
Thanks again for the PR!
