### ISSUE TITLE
Typescript?

### ISSUE THREAD

**Issue by larrywal** [dschoon/react-waves#45]
Hi - having typescript types would be super helpful with this project.  Have you thought of adding them?

**Comment by dschoon** [comment]
Thanks to @johannb75's example in his earlier issue (https://github.com/dschoon/react-waves/issues/34) I'm going to attempt to make an interface available in v4.0.1.

I'm not super familiar with Typescript, but I believe I've got it exporting as expected 👍 

Now I just need to remember to update that when the other props change 😄 

<img src="https://user-images.githubusercontent.com/3638510/98883154-9542ca80-2453-11eb-97da-68ca27f97589.png" width="500" />

If you (or anyone else) wants to add a TS example in the example directory, that could be cool!

**Comment by dschoon** [comment]
This has been released in [v4.0.1](https://www.npmjs.com/package/@dschoon/react-waves/v/4.0.1)

**Comment by johannb75** [comment]
Hey thanks for adding typescript support. I changed the interface that I made in a much simpler way.
Please check: [this issue](https://github.com/dschoon/react-waves/issues/34#issuecomment-735376787)
