### ISSUE TITLE
onPosChange inconsistent argument

### ISSUE THREAD

**Issue by SaschaVanEssen** [dschoon/react-waves#49]
When the audio is playing the argument for onPosChange seems to be the current position in seconds, but when onPosChange is triggered by clicking somewhere in the waveform the argument is a fraction. Is this the intended behaviour?

**Comment by rejochandran** [comment]
Hi @SaschaVanEssen 

onPosChange is very similar to `seek` event in weaversurfer.js ie, it returns a 0 - 1 float that represents the audio position with 0 being the start and 1 at the end 

For example, if you change your position to the middle of the audio, it would return 0.5

To get the current position of the call in seconds, just multiply the fraction value from the `onPosChange` event with the duration of the audio

Hope this helps 🙂

**Comment by SaschaVanEssen** [comment]
Thanks @rejochandran, that is indeed what happens if onPosChange is triggered by clicking in the waveform. However, if onChangePos is triggered by playing the audio it returns a float > 1.

I just noticed this even happens in the Basic Example. See what happens when you follow these steps:
1. Click play and wait fo audio and peaks -> this.state.pos is now in seconds
2. Click stop
3. Click somewhere halfway in the waveform -> this.state.pos is changed to fraction
4. Click skip -> the position goes to ~10s, because skipAhead expects this.state.pos to be in seconds and adds 10

If you keep the audio playing there is no issue, because then this.state.pos gets turned back into seconds before using skipAhead

**Comment by dschoon** [comment]
Yea, I see that I'm doing `Math.ceil(pos)` for the SEEK and AUDIO_PROCESS events, but then that is not the same in the `onPosChange` function that is pass in for the examples. I remember I did this so it would only do the callback every second and not every millisecond.

@SaschaVanEssen do you think the best approach would be for me to just update the example to also do `Math.ceil(pos)`?

I'm just not sure that forcing the `onChangePos` callback to always be an exact integer value is the right thing to do. Some people may prefer the more exact value (for instance if it's zoomed in).

**Comment by SaschaVanEssen** [comment]
The problem is that the `AUDIO_PROCESS` event returns the position in seconds (as a float, that is fine) while the `SEEK` event returns the position as a fraction. If you register for the onPosChange event you don't know wether you're going to get the position in seconds or as a fraction.

The solution would be to either change the `AUDIO_PROCESS` event to return a fraction, or change the `SEEK` event to return the seconds. This way the pos returned by the onPosChange event is always consistent.

I could create a pull request to change the `SEEK` event (`originalArgs: [duration * pos]`), but I do not know your plugin well enough to know if there are any unwanted consequences to changing the return value of the `SEEK` event

**Comment by SaschaVanEssen** [comment]
Merging pull request #52 should fix the issue

**Comment by dschoon** [comment]
There were actually a couple of issues here, so I ended up addressing them in this commit: https://github.com/dschoon/react-waves/commit/a183f4a820ed2ec1ae2edaefb679a5138bdce05c

They have been published in [v4.0.3](https://www.npmjs.com/package/@dschoon/react-waves/v/4.0.3). Sorry for the delay!

**Comment by SaschaVanEssen** [comment]
Thanks so much!
