### ISSUE TITLE
can't resolve 'react-waves'

### ISSUE THREAD

**Issue by sonalisss** [dschoon/react-waves#5]
i also have same problem.. I change that package name
import ReactWaves from '@dschoon/react-waves';
it shows no error but when we run code only the button is showing that waves part can't see
it look like this..

![screenshot 36](https://user-images.githubusercontent.com/48086608/53566523-68b52500-3b82-11e9-8748-e2d3275c2fbb.png)

**Comment by dschoon** [comment]
Are there any errors in the browsers console?

I have updated a few of the packages. Do you mind updating to v1.0.3 and trying again?

**Comment by sonalisss** [comment]
Hii,

App.js


import React from 'react';
import ReactWaves from '@dschoon/react-waves';
import './id.css';
import africa from '../src/audio/africa.mp3';
 
class App extends React.Component {
  state = {
    playing: false
  };
 
  render () {
    return (
      <div className={'container example'}>
        <div className="play button" onClick={() => { this.setState({ playing: !this.state.playing }) }}>
          { !this.state.playing ? '▶' : '■' }
        </div>
        <ReactWaves
          audioFile={africa}
          className={'react-waves'}
          options={{
            barHeight: 2,
            cursorWidth: 0,
            height: 200,
            hideScrollbar: true,
            progressColor: '#EC407A',
            responsive: true,
            waveColor: '#D1D6DA',
          }}
          volume={1}
          zoom={1}
          playing={this.state.playing}
        />
      </div>
    )
  }
}
 export default App;

 .css


body {
  margin: 30px 0;
  padding: 0;
  font-family: sans-serif;
}

.container {
  position: relative;
  margin: 0 auto;
  width: 60%;
  padding: 10px;
}

.header{
  margin: 30px 0;
}
.subheader {
  font-size: 10px;
}
.example {
  border: 1px solid gray;
}

.button {
  position: absolute;
  left: -60px;
  top: 44%;
  cursor: pointer;
  font-size: 34px;
  filter: hue-rotate(840deg);
}

i include everything same as u but still when i was click on play button it seems like this can't show waves like showing in example pls can u tell me what is my mistake exactly.


![screenshot 1](https://user-images.githubusercontent.com/48086608/53699092-a1672f80-3e0a-11e9-94d1-8eccd8219fed.png)

**Comment by dschoon** [comment]
Can you open the console and see if there are any errors?
The keyboard shortcut for this is: `Control+Shift+J`

**Comment by sonalisss** [comment]
Hii sir,
 
 There is no error in console also..any other solution for this i try from side but can't resolved it..
how can we add that audio file source i have doubt ,but i add that file code through page source.

![screenshot 3](https://user-images.githubusercontent.com/48086608/53780359-1715ed00-3f2a-11e9-9ce0-3b3743ab6d47.png)

**Comment by dschoon** [comment]
Is the audio file you're using an MP3? It seems there's an issue with your audio file.
