### ISSUE TITLE
Unable to load audio file from url (blocked by CORS policy)

### ISSUE THREAD

**Issue by pavelustenko** [dschoon/react-waves#50]
Trying to get audio from remote server url I get:
"Access to fetch at 'https://.../2ac8b776-e28d-44a9-a4c8-9d0756df396b' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled." whereas html5 audio element loads data as expected. Is there any workaround?
upd:
I added xhr:{mode:'no-cors'} to ReactWaves options, error gone from console, but seems like onWaveformReady never happens.

**Comment by dschoon** [comment]
Can you try passing in: `backend: 'MediaElement'`. I think that's how I worked around this when loading podcast episodes since I was never sure if the server was going to expect CORS headers.
```
 <ReactWaves
    audioFile={audioUrl}
    options={{
       backend: 'MediaElement',
       ...
```

**Comment by pavelustenko** [comment]
> options={{
>       backend: 'MediaElement',
>      ...
I've added MediaElement options, but this didn't help... I also tried to get mediafile as blob and init ReactWaves from it, but did not succeed in this. I also captured all request headers which chrome sends when downloading a file and tryed to send them, but result is pretty much the same.

**Comment by dschoon** [comment]
How large is the file? Is it possible to provide me the URL so I can test?
