### ISSUE TITLE
Display audio length and current time

### ISSUE THREAD

**Issue by emulienfou** [dschoon/react-waves#51]
Does this libraries offer the feature to display the full length (in seconds) of an audio file?
And does it offer also the current position when playing an audio file?

If not would it be possible to add a such feature?
Or do you have some code example to achieve that?

**Comment by emulienfou** [comment]
Nevermind, I find my answer, I need to check the examples

**Comment by Asri8655** [comment]
> Does this libraries offer the feature to display the full length (in seconds) of an audio file? And does it offer also the current position when playing an audio file?
> 
> If not would it be possible to add a such feature? Or do you have some code example to achieve that?


Any resource available?
