### ISSUE TITLE
how to style the waveform container?

### ISSUE THREAD

**Issue by kapscudi** [dschoon/react-waves#54]

**Comment by kapscudi** [comment]
I wanted to modify the padding and the margin

**Comment by dschoon** [comment]
I will be honest, I think my current approach to styling is pretty bad. This was my first open-source component.

You can pass in a `className` prop and then just do external styles... https://github.com/dschoon/react-waves/blob/master/example/src/components/LargeFilePeaksExample.js#L26

Alternatively, there are class names on the inside classes of `waveform` and `wave`... 

![image](https://user-images.githubusercontent.com/3638510/104966667-16b05f00-59a7-11eb-9cac-5e43ef6af345.png)

**Comment by dschoon** [comment]
Let me know if you have any additional questions!
