### ISSUE TITLE
How can I make react-wave play display all my tracks but play only one at the time in map()

### ISSUE THREAD

**Issue by kapscudi** [dschoon/react-waves#56]
I want to use react-wave in map() list of songs but when I play one song, they all play at the same time. How can I play just one song?

This is the handleClick function to select the track to play:

    const handlePlay = (track) => {
    if (playTrack) {
      setPlayTrack('');
    } else {
      setPlayTrack(track.pathto_audio);
    }
    console.log(playTrack)
  };

This is the map wrapped code to display all tracks but play only one at the time :

      {soundData[1].items.map((track) => (
        <div key={track.id} className="tracklist__items">
          <div className="tracklist__item" onClick={() => handlePlay(track)}>
            <PlayerButton />
          </div>

          <div className="tracklist__item">
            <ReactWaves
              className="custom"
              audioFile={track.pathto_audio}
              options={{
                barGap: 1,
                barWidth: 3,
                autoCenter: true,
                cursorWidth: 0,
                height: 50,
                hideScrollbar: true,
                progressColor: '#EC407A',
                responsive: true,
                waveColor: '#D1D6DA',
              }}
              volume={1}
              zoom={0.05}
              playing={playTrack}
            />
          </div>

          <div className="tracklist__item">
            <p>{truncate(track.name, 32)}</p>
            <span>{track.bitrate} bits/44100 hz</span>
          </div>

          <div className="tracklist__item">
            <p>
              {track.character} - {track.instrument}
            </p>
          </div>

          <div className="tracklist__item">
            <p>{track.bpm}</p>
          </div>

          <div className="tracklist__item">
            <p>{track.key}</p>
          </div>

          <p className="tracklist__item">ICON</p>
        </div>
      ))}

export default TrackList;

**Comment by dschoon** [comment]
Hey @kapscudi, I actually have an example of this on one of my projects, I will work on putting together some example code tonight for you.

**Comment by dschoon** [comment]
I think you're really close... I think you just need the `playing` prop to be more specific for that particular track...

```
   playing={playTrack === track}
```

Or maybe just use an ID from the track (or a similar unique identifier)...

```
  {soundData[1].items.map((track) => (
    <div key={track.id} className="tracklist__items">
      <div className="tracklist__item" onClick={() => handlePlay(track.id)}>
        <PlayerButton />
      </div>

      <div className="tracklist__item">
        <ReactWaves
          ...
          playing={playTrack === track.id}
        />
     </div>
```

**Comment by dschoon** [comment]
Let me know if you have any other questions!
