### ISSUE TITLE
Unhandled Rejection (ReferenceError): window is not defined

### ISSUE THREAD

**Issue by jeremythia** [dschoon/react-waves#6]
Unable to run the example. 

<img width="689" alt="Screenshot 2019-03-18 at 5 34 19 PM" src="https://user-images.githubusercontent.com/33711512/54521462-f0ce6380-49a5-11e9-97d7-5c5bc04d8650.png">

**Comment by dschoon** [comment]
Did you clone this repo and try running the example, or did you do `npm install --save @dschoon/react-waves` in your own project?

**Comment by jeremythia** [comment]
I did the nom install option in my own project.

**Comment by dschoon** [comment]
Do you have it in a public github repo that I could check out?

You aren't using server side react or anything, right?

**Comment by jakecrump** [comment]
I know this is a super old issue -- but I stumbled upon this thread in my attempt to solve the same issue, so I'm sharing what worked for me -- Note that like the OP this is using Next.js.

You can replace your normal import with:

```import dynamic from 'next/dynamic';
const ReactWaves = dynamic(import ('@dschoon/react-waves'),{ssr:false});```
