### ISSUE TITLE
Not able to update region with state

### ISSUE THREAD

**Issue by rejochandran** [dschoon/react-waves#7]
Hi,

I've included the Region and Timeline plugin and it seem to work good. I've also added the regions to the state and referenced it on the component to update it dynamically as the state changes.

```
import ReactWaves from '@dschoon/react-waves';
import Timeline from 'wavesurfer.js/dist/plugin/wavesurfer.timeline';
import Regions from 'wavesurfer.js/dist/plugin/wavesurfer.regions';

this.state = {
   playing: false,
   regions: [{
       start: 1,
       end: 3,
       color: 'hsla(400, 100%, 30%, 0.5)'
   }, {
       start: 20,
       end: 45,
       color: 'hsla(200, 50%, 70%, 0.4)'
   }]
};
...

<ReactWaves
	...
          options={{
          ...
		plugins:[
			Timeline.create({
			       container:'#timeline-container'
			}),
			Regions.create({
				Regions: this.state.regions
			}),					
		]
          }}
...
</ReactWaves>
```

However, the Region is not updated/added when the state is changed.

Am I missing any reference to an override or callback ?

Sorry for the bad code indents :)

**Comment by dschoon** [comment]
Hey @rejochandran, 
I did this quick, and need to go back and clean things up, but if you upgrade to version 1.0.8 you can now use the Regions plugin.

Here's some example code: https://github.com/dschoon/react-waves/blob/master/example/src/components/RegionsExample.js

I'm not sure all of the Event handlers are working as expected, but the major ones should be. It's mostly the mouseover, mouseleave, and event-end events that I haven't been able to get working.

Hope this helps! Let me know if you experience any issues.

**Comment by dschoon** [comment]
I just realized that you also mentioned the Timeline plugin. That still isn't setup. I'll work on adding that one next.

**Comment by rejochandran** [comment]
Hi @dschoon 

Good day! Sorry for the late reply. 
Just tested out and everything seems fine on Regions. Awesome work ! 

I am going through the code and trying to  add some functionality with respect to react-wavesurfer. Will drop in a pull request when something turns out good.

Thanks again!
